# The apt role installs all basic packages
---

- name: Install basic packages
  apt:
    name: "{{ item  }}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - git
    - htop
    - iftop
    - iotop
    - irqbalance
    - lsof
    - mtr
    - rsync
    - screen
    - strace
    - tcpdump
    - vim
    - wget
    - whois
    - tree
    - traceroute
    - unzip
    - tar
