---

- hosts: base
  user: root
  roles:
    - role: base
      tags: [base]

- hosts: latex
  user: root
  roles:
    - role: latex
      tags: [latex, tex]

- hosts: zmap
  user: root
  roles:
    - role: zmap
      tags: [zmap]

- hosts: rp
  user: root
  roles:
    - role: rp1_opt_out_webpage
      tags: [rp1, web]
