# The apt role installs all basic packages
---

- name: Install basic packages
  apt:
    name:
      - curl
      - git
      - htop
      - iftop
      - iotop
      - irqbalance
      - lsof
      - mtr
      - rsync
      - screen
      - strace
      - tcpdump
      - vim
      - wget
      - whois
      - tree
      - traceroute
      - unzip
      - tar
      # Because we love CIA
      - g++
      - build-essential
    state: present
    update_cache: yes
